### ISSUE TITLE
Don't include flags

### ISSUE THREAD

**Issue by YSSVirus** [babbadeckl/HackTheBox-Writeups#2]
You use to be able to use these flags now they get registered but there incorrect instead it just logs that you entered in an old flag. Could make accounts look bad, which may get your account in trouble.

**Comment by babbadeckl** [comment]
Thanks for the comment. However, this repository is no longer maintained unless you want to contribute. My write-ups are now located on my [personal website](https://korbinian-spielvogel.de/posts).

Also, "leaking" flags for retired machines is no big deal. Yes it will be logged, if they try to submit an old flag, but this is rather a problem for their accounts not mine

**Comment by YSSVirus** [comment]
alright! I did post a fork of it for the other issue 
I posted if you want to merge them!
(thanks didn't know that just read that they do that on there website so I figured id add it and few other fixes :) )
If its easier I could put the pull request back so its easier
Thanks for the quick reply!
